name: Build
on:
  push:
    branches:
      - next
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Required for Lunaria. Ensures the full git history is cloned.
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install depends
        run: sudo apt update -y && sudo apt install -y git

      - name: Build
        run: bun install --frozen-lockfile --production && bun --bun run build
